name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "build"

      - name: Release version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "release -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read current version
        id: read-version
        run: "echo ::set-output name=version::v$(./gradlew -q cV -Prelease.quiet)"
        if: github.ref == 'refs/heads/master'

      - name: Upload release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          artifacts: "build/libs/*.jar"
          tag: ${{ steps.read-version.outputs.version }}
